Module modPCN_ZZZ2

    Public Sub Set_AC_GpcntPCN()


        For IA As Integer = 1 To 250

            If AC(IA).libACName = "SWL-50" Then
                AC(IA).libMGpcntPCN = 1.0
            ElseIf AC(IA).libACName = "S-30" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "S-45" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "S-50" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "S-60" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "S-75" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "D-50" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "D-75" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "D-100" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "D-150" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "D-200" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "2D-100" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "2D-150" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "2D-200" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "2D-300" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "2D-400" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A300-B2 SB" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A300-B2 std" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A300-B4 std" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A300-B4 LB" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A300-600 std" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A300-600 LB" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A310-200" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A310-300" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A318-100 std" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A318-100 opt" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A319-100 std" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A319-100 opt" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A320-100" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A320-200 Twin std" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A320-200 Twin opt" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A320 Bogie" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A321-100 std" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A321-100 opt" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A321-200 std" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A321-200 opt" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A330-200 std" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A330-200 opt" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A330-200FR" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A330-200FP" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A330-300 std" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A330-300 opt" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A340-200 std" Then
                AC(IA).libMGpcntPCN = 0.39
            ElseIf AC(IA).libACName = "A340-200 opt" Then
                AC(IA).libMGpcntPCN = 0.39
            ElseIf AC(IA).libACName = "A340-300 std" Then
                AC(IA).libMGpcntPCN = 0.39
            ElseIf AC(IA).libACName = "A340-300 opt" Then
                AC(IA).libMGpcntPCN = 0.39
            ElseIf AC(IA).libACName = "A340-500 std" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "A340-500 HGW" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "A340-600 std" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "A340-600 HGW" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "A350-900 Preliminary" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A350-900" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A380n" Then
                AC(IA).libMGpcntPCN = 0.19
            ElseIf AC(IA).libACName = "A380" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "A380e" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "B707-320C" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B720B" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B717-200 HGW" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B727-100C Alternate" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Adv. B727-200C Basic" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Adv. B727-200 Option" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B737-100" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Adv. B737-200 QC" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Adv. B737-200 LP" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B737-300" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B737-400" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B737-500" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B737-600" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B737-700" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B737-800" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B737-900" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B737-900 ER" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B737 BBJ" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B737 BBJ2" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B747-100 SF" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "B747-200B Combi Mixed" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "B747-300 Combi Mixed" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "B747-400" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "B747-400ER" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "B747-8" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "B747-8F" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "B747-SP" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "B747-100 SFn" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-200B Combi Mixedn" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-300 Combi Mixedn" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-400n" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-400ERn" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-8n" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-8Fn" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-SPn" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B757-200" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B757-300" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B767-200" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B767-200 ER" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B767-300" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B767-300 ER" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B767-300 ER Freighter" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B767-400 ER" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B777-200 Baseline" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B777-200 ER" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B777-200 LR" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B777-300 Baseline" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B777-300 ER" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B777 Freighter (Preliminary)" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B787-8" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "B787-9 (Preliminary)" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "DC3" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "DC4" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "DC8-43" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "DC8-63/73" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "DC9-32" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "DC9-51" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "DC10-10" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "DC10-30/40" Then
                AC(IA).libMGpcntPCN = 0.39
            ElseIf AC(IA).libACName = "MD11ER" Then
                AC(IA).libMGpcntPCN = 0.39
            ElseIf AC(IA).libACName = "MD83" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "MD90-30 ER" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "An-124" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "An-225" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "BAe 146" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "BAC 1-11 400" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "BAC 1-11 475" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Caravelle 10" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Caravelle 12" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Canadair CL 44" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Concorde" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "CV 880M" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "CV 990" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Dash 7" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "ERJ-135" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "ERJ-140" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "ERJ-145 ER" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "ERJ-145 EP" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "ERJ-145 XR" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "EMB-170 STD" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "EMB-175 STD" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "EMB-190 STD" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "EMB-195 STD" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "F27 Friendship Mk500" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "F28 Friendship Mk1000LPT" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "F28 Friendship Mk1000HTP" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Fokker 50 HTP" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Fokker F100" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "HS125" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "HS748" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "IL62" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "IL76T" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "IL86" Then
                AC(IA).libMGpcntPCN = 0.317
            ElseIf AC(IA).libACName = "L-100-20" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "L-1011" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "TU134A" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "TU154B" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Single Wheel 2" Then
                AC(IA).libMGpcntPCN = 1.0
            ElseIf AC(IA).libACName = "Single Wheel 5" Then
                AC(IA).libMGpcntPCN = 1.0
            ElseIf AC(IA).libACName = "Single Wheel 10" Then
                AC(IA).libMGpcntPCN = 1.0
            ElseIf AC(IA).libACName = "S-3" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "S-5" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "S-10" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "S-12.5" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "S-15" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "S-20" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "S-25" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "S-30 HTP" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "S-35 HTP" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "S-40 HTP" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "D-15" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "D-20" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "D-25" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "D-30" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "D-35" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "D-40" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Aztec-D" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Baron-E-55" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "BeechJet-400" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "BeechJet-400A" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Bonanza-F-33A" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Canadair-CL-215" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Centurion-210" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Challenger-CL-604" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Chancellor-414" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Chk.Arrow-PA-28-200" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Chk.Six-PA-32" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Citation-525" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Citation-550B" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Citation-V" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Citation-VI/VII" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Citation-X" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Conquest-441" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "DC-3" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Falcon-50" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Falcon-900" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Falcon-2000" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Fokker-F-28-1000" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Fokker-F-28-2000" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Fokker-F-28-4000" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "GrnCaravan-CE-208B" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Gulfstream-G-II" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Gulfstream-G-III" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Gulfstream-G-IV" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Gulfstream-G-V" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Hawker-800" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Hawker-800XP" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "KingAir-B-100" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "KingAir-C-90" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Learjet-35A/65A" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Learjet-55" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Malibu-PA-46-350P" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Navajo-C" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "RegionalJet-200" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "RegionalJet-700" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Sabreliner-40" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Sabreliner-60" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Sabreliner-65" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Sabreliner-80" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Sarat.PA-32R-301" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Seneca-II" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Shorts-330-200" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Shorts-360" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Skyhawk-172" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Skylane-1-82" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Stationair-206" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "SuperKingAir-300" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "SuperKingAir-350" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "SuperKingAir-B200" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A400M TLL1" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A400M TLL2" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A400M LH" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "A400M LN1" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "C-5" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "C-17A" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "C-123" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "C-130" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "C-141" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "F-15C" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "F-16C" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "F/A-18C" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "KC-10" Then
                AC(IA).libMGpcntPCN = 0.39
            ElseIf AC(IA).libACName = "P-3" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "Truck Axle Single" Then
                AC(IA).libMGpcntPCN = 1.0
            ElseIf AC(IA).libACName = "Truck Axle Dual" Then
                AC(IA).libMGpcntPCN = 0.5
            ElseIf AC(IA).libACName = "Truck Axle Tandem" Then
                AC(IA).libMGpcntPCN = 0.5
            ElseIf AC(IA).libACName = "Truck Axle Dual-Tandem" Then
                AC(IA).libMGpcntPCN = 0.5
            ElseIf AC(IA).libACName = "CC3 2D" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "CC3 3D" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "3D_55lbs_243" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "3D_55lbs_220" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "CC5-6-50lbs" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "CC5-6-58lbs" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "CC5-6-65lbs" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "CC5-6-70lbs" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "CC6 45k" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "CC6 52k" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "CC6 70k" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "CC8 20k" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "CC8 20k 2D" Then
                AC(IA).libMGpcntPCN = 0.475
            ElseIf AC(IA).libACName = "C-141A ICAO Flexible" Then
                AC(IA).libMGpcntPCN = 0.45
            ElseIf AC(IA).libACName = "SWL 100 ACN" Then
                AC(IA).libMGpcntPCN = 1.0
            ElseIf AC(IA).libACName = "A340-200 std Belly" Then
                AC(IA).libMGpcntPCN = 0.17
            ElseIf AC(IA).libACName = "A340-200 opt Belly" Then
                AC(IA).libMGpcntPCN = 0.17
            ElseIf AC(IA).libACName = "A340-300 std Belly" Then
                AC(IA).libMGpcntPCN = 0.17
            ElseIf AC(IA).libACName = "A340-300 opt Belly" Then
                AC(IA).libMGpcntPCN = 0.17
            ElseIf AC(IA).libACName = "A340-500 std Belly" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "A340-500 HGW Belly" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "A340-600 std Belly" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "A340-600 HGW Belly" Then
                AC(IA).libMGpcntPCN = 0.95
            ElseIf AC(IA).libACName = "A380n Belly" Then
                AC(IA).libMGpcntPCN = 0.285
            ElseIf AC(IA).libACName = "B747-100 SFn Belly" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-200B Combi Mixedn Belly" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-300 Combi Mixedn Belly" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-400n Belly" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-400ERn Belly" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-8n Belly" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-8Fn Belly" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "B747-SPn Belly" Then
                AC(IA).libMGpcntPCN = 0.238
            ElseIf AC(IA).libACName = "DC10-30/40 Belly" Then
                AC(IA).libMGpcntPCN = 0.17
            ElseIf AC(IA).libACName = "MD11ER Belly" Then
                AC(IA).libMGpcntPCN = 0.17
            ElseIf AC(IA).libACName = "IL86 Belly" Then
                AC(IA).libMGpcntPCN = 0.317
            ElseIf AC(IA).libACName = "KC-10 Belly" Then
                AC(IA).libMGpcntPCN = 0.17
            End If
        Next


    End Sub

End Module
